# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolov8-shared-pvc  # Nama PVC yang akan kita gunakan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi